### ISSUE TITLE
Do we need an endpoint to look up a specific comment id?

### ISSUE THREAD

**Issue by christiankm** [Nordic-T/API#1]
Do we need an endpoint for getting a specific comment by id?

Something like **/comments/:id**

Normally you would view all comments in a discussion.

**Comment by fbjerggaard** [comment]
Probably yes, since that would be the endpoint for posting an edit to a comment right?

**Comment by christiankm** [comment]
Well, I was thinking that would be done using **PUT /discussion/id/comments/id**

**Comment by fbjerggaard** [comment]
Then that's what we do :)

**Comment by christiankm** [comment]
We can do both though - but unless there's a specific need, I think I'll keep it simple.

**Comment by fbjerggaard** [comment]
Agreed - let's leave it out for now unless we find a need for it.
